version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

  migrate:
    image: migrate/migrate:v4.14.1
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "sh", "-c",
      "until nc -z db 5432; do sleep 2; done; migrate -path=/migrations -database postgres://$${DATABASE_USER}:$${DATABASE_PASSWORD}@db:5432/$${DATABASE_NAME}?sslmode=disable up"
    ]
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - db

  # Сервис для тестирования
  test:
    build: .
    entrypoint: ["/bin/sh", "-c", "go test ./... -v"]
    depends_on:
      - db
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
      - db
      - migrate
      - test
    volumes:
      - ./.env:/src/.env
    command: ["/bin/server"]

volumes:
  db_data:
